program DRM;

uses
  Forms,
  MainUnit in 'MainUnit.pas' {FMain},
  LoginUnit in 'LoginUnit.pas' {FLogin},
  DMUnit in 'DMUnit.pas' {DM: TDataModule},
  UserUnit in 'UserUnit.pas' {FUser},
  FpictureUnit in 'FpictureUnit.pas' {FPicture},
  ReceptionUnit in 'ReceptionUnit.pas' {frmReception},
  SubCoUnit in 'SubCoUnit.pas' {frmSubCo},
  CalculatUnit in 'CalculatUnit.pas',
  ClosedUnit in 'ClosedUnit.pas' {frmClosed},
  AddClosedUnit in 'AddClosedUnit.pas' {frmAddClosed},
  DelClosedUnit in 'DelClosedUnit.pas' {frmDelClosed},
  CreditUnit in 'CreditUnit.pas' {frmCredit},
  ShareUnit in 'ShareUnit.pas',
  UFarsiDate in 'UfarsiDate.pas',
  ShiftUnit in 'ShiftUnit.pas' {frmShift},
  ByUnit in 'ByUnit.pas' {frmBy},
  ViewReceptionUnit in 'ViewReceptionUnit.pas' {frmViewReception},
  CreateCardUnit in 'CreateCardUnit.pas' {frmCreateCard},
  SubBargainCoInfoUnit in 'SubBargainCoInfoUnit.pas' {frmSubBargainCoInfo},
  CardTypeInfoUnit in 'CardTypeInfoUnit.pas' {frmCardTypeInfo},
  ProductUnit in 'ProductUnit.pas' {frmProduct},
  VahedUnit in 'VahedUnit.pas' {frmVahed},
  VahedInfoUnit in 'VahedInfoUnit.pas' {frmVahedInfo},
  MenuUnit in 'MenuUnit.pas' {frmMenu},
  KalaInfoUnit in 'KalaInfoUnit.pas' {frmKalaInfo},
  PrePrintUnit in 'PrePrintUnit.pas' {frmPrePrint},
  qrSmallMenuFactorUnit in 'qrSmallMenuFactorUnit.pas' {qrSmallMenuFactor: TQuickRep},
  ParameterUnit in 'ParameterUnit.pas' {frmParameter},
  DescriptionUnit in 'DescriptionUnit.pas' {frmDescription},
  DescriptionInfoUnit in 'DescriptionInfoUnit.pas' {frmDescriptionInfo},
  qrChargeCreditUnit in 'qrChargeCreditUnit.pas' {qrChargeCredit: TQuickRep},
  qrCreditInfoUnit in 'qrCreditInfoUnit.pas' {qrCreditInfo: TQuickRep},
  SearchCustomerUnit in 'SearchCustomerUnit.pas' {frmSearchKeyNumber},
  SabegheMoshtariUnit in 'SabegheMoshtariUnit.pas' {frmSabegheMoshtari},
  AdvansedSearchUnit in 'AdvansedSearchUnit.pas' {frmAdvansedSearch},
  qrReceptionUnit in 'qrReceptionUnit.pas' {qrReception: TQuickRep},
  qrExitReportUnit in 'qrExitReportUnit.pas' {qrExitReport: TQuickRep},
  qrExitReport2Unit in 'qrExitReport2Unit.pas' {qrExitReport2: TQuickRep},
  ReceptionListUnit in 'ReceptionListUnit.pas' {frmReceptionList},
  CreditListUnit in 'CreditListUnit.pas' {frmCreditList},
  EnterUnit in 'EnterUnit.pas' {frmEnter},
  qrExitUnit in 'qrExitUnit.pas' {qrExit: TQuickRep},
  WorkSectionUnit in 'WorkSectionUnit.pas' {frmWorkSection},
  WorkSectionInfoUnit in 'WorkSectionInfoUnit.pas' {frmWorkSectionInfo},
  SalesReportUnit in 'SalesReportUnit.pas' {frmSalesReport},
  UserInfoUnit in 'UserInfoUnit.pas' {frmUserInfo},
  ManagerUnit in 'ManagerUnit.pas' {frmManager},
  DailyReportUnit in 'DailyReportUnit.pas' {frmDailyReport},
  LockerMapUnit in 'LockerMapUnit.pas' {frmLockerMap},
  BargainInfoUnit in 'BargainInfoUnit.pas' {frmBargainInfo},
  qrFactorsReportUnit in 'qrFactorsReportUnit.pas' {qrFactorsReport: TQuickRep},
  GroupKalaUnit in 'GroupKalaUnit.pas' {frmGroupKala},
  qrGroupKalaUnit in 'qrGroupKalaUnit.pas' {qrGroupKala: TQuickRep},
  qrCashUnit in 'qrCashUnit.pas' {qrCash: TQuickRep},
  qrFactorCheckUnit in 'qrFactorCheckUnit.pas' {qrFactorCheck: TQuickRep},
  qrCardGroupUnit in 'qrCardGroupUnit.pas' {qrCardGroup: TQuickRep},
  MenuPasswordUnit in 'MenuPasswordUnit.pas' {frmMenuPassword},
  qrDailyReportUnit in 'qrDailyReportUnit.pas' {qrReportDaily: TQuickRep},
  qrResturentDailyReportUnit in 'qrResturentDailyReportUnit.pas' {qrDailyReportResturent: TQuickRep},
  qrCreditModUnit in 'qrCreditModUnit.pas' {qrCreditMod: TQuickRep},
  CreditModUnit in 'CreditModUnit.pas' {frmCreditMod},
  BargainUnit in 'BargainUnit.pas' {frmBargain},
  ViewBargainUnit in 'ViewBargainUnit.pas' {frmViewBargain},
  CheckCardUnit in 'CheckCardUnit.pas' {frmCheckCard},
  SalesFactorUnit in 'SalesFactorUnit.pas' {frmSalesFactor},
  qrCompanyBargainUnit in 'qrCompanyBargainUnit.pas' {qrCompanyBargain: TQuickRep},
  CardReportUnit in 'CardReportUnit.pas' {frmCardReport},
  qrCardReportUnit in 'qrCardReportUnit.pas' {qrCardReport: TQuickRep},
  qrCardNumberUnit in 'qrCardNumberUnit.pas' {qrCardNumber: TQuickRep},
  EdtReceptionUnit in 'EdtReceptionUnit.pas' {frmEdtReception},
  SummeryCardUnit in 'SummeryCardUnit.pas' {frmSummeryCard},
  ReceptionChartUnit in 'ReceptionChartUnit.pas' {frmReceptionChart},
  FactorPrintUnit in 'FactorPrintUnit.pas' {frmFactorPrint},
  qrFactorPrintUnit in 'qrFactorPrintUnit.pas' {qrFctorPrint: TQuickRep},
  ActiveLockerUnit in 'ActiveLockerUnit.pas' {frmActiveLocker},
  ChargeManagerUnit in 'ChargeManagerUnit.pas' {frmChargeManager},
  qrShopUnit in 'qrShopUnit.pas' {qrShop: TQuickRep},
  DeleteInfoUnit in 'DeleteInfoUnit.pas' {frmDeleteInfo},
  GardUnit in 'GardUnit.pas' {frmGard},
  qrGardUnit in 'qrGardUnit.pas' {qrGard: TQuickRep},
  BarCodeUnit in 'BarCodeUnit.pas' {frmBarCode},
  qrBargainUnit in 'qrBargainUnit.pas' {qrBargain: TQuickRep},
  qrUsedListCardUnit in 'qrUsedListCardUnit.pas' {qrUsedCardList: TQuickRep},
  VIPUnit in 'VIPUnit.pas' {frmVIP},
  GroupUnit in 'GroupUnit.pas' {frmGroup},
  ExpireDateUnit in 'ExpireDateUnit.pas' {frmExpireDate},
  SubBargainUnit in 'SubBargainUnit.pas' {frmSubBargain},
  CompanyUnit in 'CompanyUnit.pas' {frmCompany},
  UnitCompanyInfo in 'UnitCompanyInfo.pas' {frmCompanyInfo},
  qrSubBargainUnit in 'qrSubBargainUnit.pas' {qrSubBargain: TQuickRep},
  DeActiveUnit in 'DeActiveUnit.pas' {frmDeActiveCard},
  ModCreditReportUnit in 'ModCreditReportUnit.pas' {frmModCreditReport},
  NotCheckedCardUnit in 'NotCheckedCardUnit.pas' {frmNotCheckedCard},
  TempBargainUnit in 'TempBargainUnit.pas' {frmTempBargain},
  NotAcceptBargainUnit in 'NotAcceptBargainUnit.pas' {frmNotAcceptBargain},
  ReceptionCardUnit in 'ReceptionCardUnit.pas' {frmReceptionCard},
  TadilSharjeUnit in 'TadilSharjeUnit.pas' {frmTadilSharje},
  AmareForooshUnit in 'AmareForooshUnit.pas' {frmAmareForoosh},
  qrAmareForooshUnit in 'qrAmareForooshUnit.pas' {qrAmareForoosh: TQuickRep},
  qrReceptionWithCard in 'qrReceptionWithCard.pas' {reReceptionWithCard: TQuickRep},
  LabiCashierUnit in 'LabiCashierUnit.pas' {frmLabiCashier},
  CashUnit in 'CashUnit.pas' {frmCash},
  qrSCashUnit in 'qrSCashUnit.pas' {qrSCash: TQuickRep},
  SendSMSUnit in 'SendSMSUnit.pas' {frmSendSMS},
  ReceptionGroupUnit in 'ReceptionGroupUnit.pas' {frmReceptionGroup},
  qrSendChargeUnit in 'qrSendChargeUnit.pas' {qrSendCharge: TQuickRep},
  qrChangeLockerUnit in 'qrChangeLockerUnit.pas' {qrChangeLocker: TQuickRep},
  qrReturnFromExitUnit in 'qrReturnFromExitUnit.pas' {qrReturnFromExit: TQuickRep},
  MenuListUnit in 'MenuListUnit.pas' {frmMenuList},
  qrManuListUnit in 'qrManuListUnit.pas' {qrMenuList: TQuickRep},
  EnterOrderUnit in 'EnterOrderUnit.pas' {frmEnterOrder},
  DelFactorsUnit in 'DelFactorsUnit.pas' {frmDelFactor},
  ChangeToUnit in 'ChangeToUnit.pas' {frmChangeTo},
  ComputerUnit in 'ComputerUnit.pas' {frmComputer},
  LockerWomenUnit in 'LockerWomenUnit.pas' {frmLockerWomen},
  SectionUnit in 'SectionUnit.pas' {frmSection},
  VisitorUnit in 'VisitorUnit.pas' {frmVisitor},
  CustomerUnit in 'CustomerUnit.pas' {frmCustomer},
  SectionInfoUnit in 'SectionInfoUnit.pas' {frmSectionInfo},
  VisitorInfoUnit in 'VisitorInfoUnit.pas' {frmVisitorInfo},
  CustomerInfoUnit in 'CustomerInfoUnit.pas' {frmCustomerInfo},
  SectionAndVisitorUnit in 'SectionAndVisitorUnit.pas' {frmSectionAndVisitor},
  SellUnit in 'SellUnit.pas' {frmSell},
  qrVisitorUnit in 'qrVisitorUnit.pas' {qrVisitor: TQuickRep},
  qrCustomerUni in 'qrCustomerUni.pas' {qrCustomer: TQuickRep},
  qrSellUni in 'qrSellUni.pas' {qrSell: TQuickRep},
  ManageOfUserUnit in 'ManageOfUserUnit.pas' {frmManegeofUser},
  qrDayReportUnit in 'qrDayReportUnit.pas' {qrDayReport: TQuickRep},
  HealthCardUnit in 'HealthCardUnit.pas' {frmHealthCard},
  WorkSectionHealthCardUnit in 'WorkSectionHealthCardUnit.pas' {frmWorkSectionHealthCard},
  qrEnterOrderUnit in 'qrEnterOrderUnit.pas' {qrEnterOrder: TQuickRep},
  OrderSelectUnit in 'OrderSelectUnit.pas' {frmOrderSelect},
  ExportFactorUnit in 'ExportFactorUnit.pas' {frmExportFactor},
  qrExportFactorUnit in 'qrExportFactorUnit.pas' {qrExportFactor: TQuickRep},
  OrderDiscountUnit in 'OrderDiscountUnit.pas' {frmOrderDiscount},
  AvgPriceUnit in 'AvgPriceUnit.pas' {frmAvgPrice},
  ActiveUserUnit in 'ActiveUserUnit.pas' {frmActiveUser},
  PQCUnit in 'PQCUnit.pas' {frmPQC},
  PQCPersonInfoUnit in 'PQCPersonInfoUnit.pas' {frmPQCPersonInfo},
  ChangingRoom2Unit in 'ChangingRoom2Unit.pas' {frmChangingRooms2},
  qrLockerPrintUnit in 'qrLockerPrintUnit.pas' {qrLockerPrint: TQuickRep},
  ReturnTicketUnit in 'ReturnTicketUnit.pas' {qrReturnTicket: TQuickRep},
  CardListUnit in 'CardListUnit.pas' {frmCardList},
  OrderUnit in 'OrderUnit.pas' {frmOrder},
  SetLockerAndUserUnit in 'SetLockerAndUserUnit.pas' {frmSetLockerAndUser},
  OrderCustomerUnit in 'OrderCustomerUnit.pas' {frmOrderCustomer},
  CheckEnterUnit in 'CheckEnterUnit.pas' {frmCheckEnter},
  LastEnterUnit in 'LastEnterUnit.pas' {frmLastEnter},
  HotelsUnit in 'HotelsUnit.pas' {frmHotels},
  HotelInfoUnit in 'HotelInfoUnit.pas' {frmHotelInfo},
  HotelreceptionUnit in 'HotelreceptionUnit.pas' {frmHotelReception},
  HotelsInfoUnit in 'HotelsInfoUnit.pas' {frmHotelsInfo},
  qrHotelUnit in 'qrHotelUnit.pas' {qrHotels: TQuickRep},
  HotelReceptionInfoUnit in 'HotelReceptionInfoUnit.pas' {frmHotelReceptionInfo},
  HotelReceptionReportUnit in 'HotelReceptionReportUnit.pas' {frmHotelReceptionReport},
  qrOrderHotelDailyUnit in 'qrOrderHotelDailyUnit.pas' {qrOrderHotel: TQuickRep},
  MakedGoodsUnit in 'MakedGoodsUnit.pas' {frmMakedGoods},
  ReceptionCardPriceUnit in 'ReceptionCardPriceUnit.pas' {frmREceptionCardPrice},
  qrReceptionCardPriceUnit in 'qrReceptionCardPriceUnit.pas' {qrReceptionCardPrice: TQuickRep},
  qrOrderHotelDailyReportUnit in 'qrOrderHotelDailyReportUnit.pas' {qrOrderHotelReport: TQuickRep},
  UserAttractionUnit in 'UserAttractionUnit.pas' {frmUsedAttraction},
  SlidesReportUnit in 'SlidesReportUnit.pas' {frmSlidesReport},
  OneSlideReportUnit in 'OneSlideReportUnit.pas' {frmOneSlidesReport},
  MessageUnit in 'MessageUnit.pas' {frmMessage},
  NotIssueExitUnit in 'NotIssueExitUnit.pas' {qrNotIssueExit: TQuickRep},
  IssueTicketUnit in 'IssueTicketUnit.pas' {frmIssueTicket},
  WebReceptionUnit in 'WebReceptionUnit.pas' {frmWebReception},
  WebReceptionInfoUnit in 'WebReceptionInfoUnit.pas' {frmWebReceptionInfo},
  WebGroupUnit in 'WebGroupUnit.pas' {frmWebGroup},
  LottoryUnit in 'LottoryUnit.pas' {frmLottory},
  TaxiUnit in 'TaxiUnit.pas' {frmTaxi},
  qrTaxiUnit in 'qrTaxiUnit.pas' {qrTaxi: TQuickRep},
  OrderTypeInfoUnit in 'OrderTypeInfoUnit.pas' {frmOrderTypeInfo},
  ShiftSammeryUnit in 'ShiftSammeryUnit.pas' {frmShiftSammery},
  PrivateTaxiInfoUnit in 'PrivateTaxiInfoUnit.pas' {frmPrivateTaxiInfo},
  CreditGroupUnit in 'CreditGroupUnit.pas' {frmCreditGroup},
  CreditCardUnit in 'CreditCardUnit.pas' {frmCreditCard},
  SubsetCreditCardUnit in 'SubsetCreditCardUnit.pas' {frmSubsetCreditCard},
  CreditCardGroupInfoUnit in 'CreditCardGroupInfoUnit.pas' {frmCreditCardGroupInfo},
  CreditCardChargeUnit in 'CreditCardChargeUnit.pas' {frmCreditCardCharge},
  CredeitCardInfoUnit in 'CredeitCardInfoUnit.pas' {frmCreditCardInfo},
  CreditCardTicketUnit in 'CreditCardTicketUnit.pas' {frmCreditCardTicket},
  CreditCardChargeReportUnit in 'CreditCardChargeReportUnit.pas' {frmCreditCardChargeReport},
  qrCreditCardPrint1Unit in 'qrCreditCardPrint1Unit.pas' {qrCreditCard1: TQuickRep},
  qrCreditCardBargainUnit in 'qrCreditCardBargainUnit.pas' {qrBargainCreditCard: TQuickRep},
  SpecialCreditCardReportUnit in 'SpecialCreditCardReportUnit.pas' {frmSpecialCreditCardReport},
  CreditCardTypeInfo in 'CreditCardTypeInfo.pas' {frmCreditCardTypeInfo},
  CreditCardDiscountUnit in 'CreditCardDiscountUnit.pas' {frmCreditCard_Discount},
  CreditCardListUnit in 'CreditCardListUnit.pas' {frmCreditCardList},
  ReceptionCreditCardUnit in 'ReceptionCreditCardUnit.pas' {frmReceptionCreditCard},
  IssueCreditCardTicketUnit in 'IssueCreditCardTicketUnit.pas' {frmIssueCreditCardTicket},
  GetAccessToLoginUnit in 'GetAccessToLoginUnit.pas' {frmGetAccessToLogin},
  setActiveTaxiUnit in 'setActiveTaxiUnit.pas' {frmSetActiveTaxi},
  AddOnServicesUnit in 'AddOnServicesUnit.pas' {frmAddOnServices},
  qrAddOnServicesUnit in 'qrAddOnServicesUnit.pas' {qrAddOnServices: TQuickRep},
  SpecialGuestCreditUnit in 'SpecialGuestCreditUnit.pas' {frmSpecialGuestCredit},
  UnitSummaryCreditCard in 'UnitSummaryCreditCard.pas' {frmSummaryCreditCard},
  ServiceCenterInfoUnit in 'ServiceCenterInfoUnit.pas' {frmService_center_info},
  qrWarmDeleteUnit in 'qrWarmDeleteUnit.pas' {qrWarmDelete: TQuickRep},
  HotelSectionInfoUnit in 'HotelSectionInfoUnit.pas' {frmHotelSectionInfo},
  LockerRoom2Unit in 'LockerRoom2Unit.pas' {frmLockerRoom2},
  EnterQueueUnit in 'EnterQueueUnit.pas' {frmEnterQueue},
  ManageQueueUnit in 'ManageQueueUnit.pas' {frmManageQueue},
  ReserveQueueListUnit in 'ReserveQueueListUnit.pas' {frmReserveQueueList},
  ActiveServiceProviderUnit in 'ActiveServiceProviderUnit.pas' {frmActiveServiceProvider},
  UseQueueUnit in 'UseQueueUnit.pas' {frmUseQueue},
  QueueTVUnit in 'QueueTVUnit.pas' {frmQueueTV},
  WebResellersInfoUnit in 'WebResellersInfoUnit.pas' {frmWebResellersInfo},
  PosUnit in 'PosUnit.pas' {frmPos},
  PosResellerInfoUnit in 'PosResellerInfoUnit.pas' {frmPosResellerInfo},
  PosReceptionInfoUnit in 'PosReceptionInfoUnit.pas' {frmPosReceptionInfo},
  WebResellerGroupInfoUnit in 'WebResellerGroupInfoUnit.pas' {frmWebResellerGroup},
  GroupLockerMapPhaz2Unit in 'GroupLockerMapPhaz2Unit.pas' {frmGroupLockerMapPhaz2},
  LockerWomen2Unit in 'LockerWomen2Unit.pas' {frmLockerWomen2},
  PcPosInfoUnit in 'PcPosInfoUnit.pas' {frmPcPosInfo},
  PcPosUnit in 'PcPosUnit.pas' {frmPcPos},
  HotelTicketingUnit in 'HotelTicketingUnit.pas' {frmHotelTicketing},
  AppMenuAccessUnit in 'AppMenuAccessUnit.pas' {frmAppMenuAccess},
  InternetReceptionUnit in 'InternetReceptionUnit.pas' {frmInternetReception},
  HotelReceptionSummeryUnit in 'HotelReceptionSummeryUnit.pas' {frmHotelTicketSummery},
  showBargainInfoUnit in 'showBargainInfoUnit.pas' {frmShowBargainInfo},
  OrderTypeUnit in 'OrderTypeUnit.pas' {frmOrderType},
  ReceptionSummaryReportUnit in 'ReceptionSummaryReportUnit.pas' {frmReceptionSummaryReport},
  PosTransactionsUnit in 'PosTransactionsUnit.pas' {frmPosTransactions},
  UserTypeUnit in 'UserTypeUnit.pas' {frmUserType},
  HOtelTicketTypeInfoUnit in 'HOtelTicketTypeInfoUnit.pas' {frmHotelTicketTypeInfo},
  internetUsageDateUnit in 'internetUsageDateUnit.pas' {frminternetUsageDate},
  KalaGroupInfoUnit in 'KalaGroupInfoUnit.pas' {frmKalaGroupInfo},
  KalaGroupUnit in 'KalaGroupUnit.pas' {frmKalaGroup},
  UniMobileInternetReportt in 'UniMobileInternetReportt.pas' {frmInternetMobileReport},
  webReceptionSystemIdReportUnit in 'webReceptionSystemIdReportUnit.pas' {frmWebReceptionSystemIdReport},
  webReceptionMobileUnit in 'webReceptionMobileUnit.pas' {frmWebRecptionMobile},
  webReceptionReportChartPerDayUnit in 'webReceptionReportChartPerDayUnit.pas' {frmWebReceptionReportChartPerDay},
  PSPInfoUnit in 'PSPInfoUnit.pas' {frmPSPInfo},
  ShopsReportUnit in 'ShopsReportUnit.pas' {frmShopsReport},
  ManageLockersUnit in 'ManageLockersUnit.pas' {frmManageLockers},
  LockerRoominfoUnit in 'LockerRoominfoUnit.pas' {frmLockerRoomInfo},
  SellByBarcodeUnit in 'SellByBarcodeUnit.pas' {frmSaleByBarcode},
  CreditCardPriceGroupUnit in 'CreditCardPriceGroupUnit.pas' {frmCreditCardPriceGroup},
  CreditCardPriceGroupInfoUnit in 'CreditCardPriceGroupInfoUnit.pas' {frmCreditCardPriceGroupInfo},
  ReceptionCreditCardReportUnit in 'ReceptionCreditCardReportUnit.pas' {frmReceptionCreditCardReport},
  GenderInfoUnit in 'GenderInfoUnit.pas' {frmGenderInfo},
  CreditCardGroupReceptionUnit in 'CreditCardGroupReceptionUnit.pas' {frmCreditCardGroupReception},
  ManageShiftsUnit in 'ManageShiftsUnit.pas' {frmManageShift},
  ShiftInfoUnit in 'ShiftInfoUnit.pas' {frmShiftInfo},
  CreditGroupAndShiftUnit in 'CreditGroupAndShiftUnit.pas' {frmCreditGroupAndShift},
  StartShiftUnit in 'StartShiftUnit.pas' {frmStartShift},
  AgeCategoryUnit in 'AgeCategoryUnit.pas' {frmAgeCategory},
  LessonTypeUnit in 'LessonTypeUnit.pas' {frmLessonType},
  LessonUnit in 'LessonUnit.pas' {frmLesson},
  AgeCategoryInfoUnit in 'AgeCategoryInfoUnit.pas' {frmAgeCategoryInfo},
  LeesonTypeInfoUnit in 'LeesonTypeInfoUnit.pas' {frmLessonTypeInfo},
  LessonGroupInfoUnit in 'LessonGroupInfoUnit.pas' {frmLessonGroupInfo},
  LessonGroupUnit in 'LessonGroupUnit.pas' {frmLessonGroup},
  creditCardsListUnit in 'creditCardsListUnit.pas' {frmCreditCardsList},
  LessonInfoUnit in 'LessonInfoUnit.pas' {frmLessonInfo},
  EnrollmentUnit in 'EnrollmentUnit.pas' {frmEnrollment},
  enrollmentInfoUnit in 'enrollmentInfoUnit.pas' {frmEnrollmentInfo},
  TuitionPayUnit in 'TuitionPayUnit.pas' {frmTuitionPay},
  PayTuitionListUnit in 'PayTuitionListUnit.pas' {frmPayTuitionList},
  OrderDiscountInfoUnit in 'OrderDiscountInfoUnit.pas' {frmOrderDiscountInfo},
  PoolsUnit in 'PoolsUnit.pas' {frmPools},
  PoolInfoUnit in 'PoolInfoUnit.pas' {frmPoolsInfo},
  RentUnit in 'RentUnit.pas' {frmRent},
  RentPoolInfoUnit in 'RentPoolInfoUnit.pas' {frmRentPoolInfo},
  studentUnit in 'studentUnit.pas' {frmStudent},
  StudentInfoUnit in 'StudentInfoUnit.pas' {frmStudentInfo},
  StudentEnrollmentUnit in 'StudentEnrollmentUnit.pas' {frmStudentEnrollment},
  SchoolTuitionPayUnit in 'SchoolTuitionPayUnit.pas' {frmSchoolTuitionPay},
  TermUnit in 'TermUnit.pas' {frmTerm},
  TermInfoUnit in 'TermInfoUnit.pas' {frmTermInfo},
  PayedSchoolTuitionUnit in 'PayedSchoolTuitionUnit.pas' {frmPayedSchoolTuition},
  EmployeeGroupUnit in 'EmployeeGroupUnit.pas' {frmEmployeeGroup},
  EmployeeGroupInfoUnit in 'EmployeeGroupInfoUnit.pas' {frmEmployeeGroupInfo},
  EmployeeUnit in 'EmployeeUnit.pas' {frmEmployee},
  EmployeeInfoUnit in 'EmployeeInfoUnit.pas' {frmEmployeeInfo},
  InOutUnit in 'InOutUnit.pas' {frmInOut},
  InOutListUnit in 'InOutListUnit.pas' {frmInOutList},
  PoolSupervisorUnit in 'PoolSupervisorUnit.pas' {frmPoolSupervisor},
  PoolSupervisorInfoUnit in 'PoolSupervisorInfoUnit.pas' {frmPoolSupervisorInfo},
  PoolAndSupervisorUnit in 'PoolAndSupervisorUnit.pas' {frmPoolAndSupervisor},
  TermAndSupervisorUnit in 'TermAndSupervisorUnit.pas' {frmTermAndSupervisor},
  InstructorUnit in 'InstructorUnit.pas' {frmInstructor},
  InstructorInfoUnit in 'InstructorInfoUnit.pas' {frmInstructorInfo},
  CourseUnit in 'CourseUnit.pas' {frmCourse},
  CourseInfoUnit in 'CourseInfoUnit.pas' {frmCourceInfo},
  ClassUnit in 'ClassUnit.pas' {frmClass},
  StudentAndClassUnit in 'StudentAndClassUnit.pas' {frmStudentAndClass},
  ClassInfoUnit in 'ClassInfoUnit.pas' {frmClassInfo},
  ClassReportUnit in 'ClassReportUnit.pas' {frmClassReport},
  FinacialObligationUnit in 'FinacialObligationUnit.pas' {frmFinacialObligation},
  MyDate in 'MyDate.pas',
  RollCallUnit in 'RollCallUnit.pas' {frmRollCall},
  GeneralReportUnit in 'GeneralReportUnit.pas' {frmGeneralReport},
  TermScheduleInfoUnit in 'TermScheduleInfoUnit.pas' {frmTermScheduleInfo},
  holidayUnit in 'holidayUnit.pas' {frmHoliday},
  AutoEnrollmentUnit in 'AutoEnrollmentUnit.pas' {frmAutoEnrollment},
  LockersUnit in 'LockersUnit.pas' {frmLockers},
  LockerLendUnit in 'LockerLendUnit.pas' {frmLendLockers},
  LockerRoomUnit in 'LockerRoomUnit.pas' {frmLockerRoom},
  ComputerGroupUnit in 'ComputerGroupUnit.pas' {frmComputerGroup},
  ComputerAndCompuetrGroupUnit in 'ComputerAndCompuetrGroupUnit.pas' {frmComputerAndCompueterGroup},
  ComputerGroupInfoUnit in 'ComputerGroupInfoUnit.pas' {frmComputerGroupInfo},
  UserAndComputerGroupUnit in 'UserAndComputerGroupUnit.pas' {frmUserAndComputerGroup},
  ChangingLockerNumberUnit in 'ChangingLockerNumberUnit.pas' {frmChangingLockerNumber};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TFMain, FMain);
  Application.Run;
end.
